openapi: 3.0.0
info:
  title: DevAppMs
  version: 1.0.0
servers:
  - url: https://devjam-lab.azurewebsites.net
  - url: http://localhost:7071
paths:
  /receive/{tenantId}:
    post:
      parameters:
        - in: path
          name: tenantId   # Note the name is  the same as in the path
          required: true
          schema:
            type: string
          description: Tenant id
      tags:
        - Git events
      summary: Register git events
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                version: 
                  type: string
                events: 
                  type: array
                  items:
                    type: object
                    $ref: "#/components/schemas/GitEvent"              
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Date:
              schema:
                type: string
                example: Thu, 24 Aug 2023 20:47:20 GMT
            Server:
              schema:
                type: string
                example: Kestrel
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                  code: 
                    type: number
                  tenantId:
                    type: string
                  count:
                    type: number
              example:
                status: OK
                code: 0
                tenantId: my tenant3
                count: 2
components:
  schemas:
    GitEvent:
      type: object
      properties:
          gitlog: 
            type: string
          oper: 
            type: string
          remote: 
            type: string
          diff: 
            type: string
          id: 
            type: string
          decoded: 
            type: object
            properties: 
              commit: 
                type: string
              author: 
                type: object
                properties: 
                  name: 
                    type: string
                  email: 
                    type: string
              date: 
                type: string
              message: 
                type: string
              changes: 
                type: array
              changeSummary: 
                type: object
                properties: 
                  raw: 
                    type: string
                  files: 
                    type: integer
                    format: int32
                  inserts: 
                    type: integer
                    format: int32
                  deletions: 
                    type: integer
                    format: int32
          ct: 
            type: integer
            format: int64
          s: 
            type: integer
            format: int32
          e: 
            type: object
            properties: 
              ec: 
                type: number
              em: 
                type: number
              et: 
                type: integer
                format: int32
              er: 
                type: number
              ed: 
                type: number
              e: 
                type: number    