#!/bin/sh
echo "POST-COMMIT LOG"

GIT_LOG=`git log -1 HEAD`
echo $GITLOG

POST_BODY="{\"gitlog\":\"$GITLOG\"}"

curl -S -s -H "Content-Type: application/json" -d "$POST_BODY" http://localhost:5001/v1/hooks/commit


exit 0