#!/bin/sh
GIT_LOG=`git log --stat -1 HEAD | base64`
GIT_DIFF=`git show --unified | base64`
REMOTE=`git config --get remote.origin.url`
POST_BODY="{\"gitlog\":\"$GIT_LOG\",\"oper\":\"commit\",\"remote\":\"$REMOTE\",\"diff\":\"$GIT_DIFF\"}"
curl -S -s -H "Content-Type: application/json" -d "$POST_BODY" http://localhost:5001/v1/hooks/commit




































exit 0