#!/bin/sh
GIT_LOG=`git log --stat -1 HEAD | base64`
GIT_DIFF=`git show --unified=0 | base64`
REMOTE=`git config --get remote.origin.url`
LOCAL=`git rev-parse --show-toplevel`
ACCOUNT=""
USER=""
PROJECT=""

FINAL_REMOTE=""

if [ -n "$REMOTE" ]; then
    FINAL_REMOTE=$REMOTE
else
    FINAL_REMOTE=$LOCAL
fi

POST_BODY="{\"gitlog\":\"$GIT_LOG\",\"oper\":\"commit\",\"remote\":\"$FINAL_REMOTE\",\"diff\":\"$GIT_DIFF\",\"account\":\"$ACCOUNT\",\"user\":\"$USER\",\"project\":\"$PROJECT\"}"
echo $POST_BODY | curl -S -s -H "Content-Type: application/json" -d @- http://localhost:5001/v1/hooks/commit

exit 0