#!/bin/sh
# echo "PRE-PUSH LOG"

GIT_LOG=`git log --stat -1 HEAD | base64`
REMOTE=`git config --get remote.origin.url`
LOCAL=`git rev-parse --show-toplevel`

FINAL_REMOTE=""

if [ -n "$REMOTE" ]; then
    FINAL_REMOTE=$REMOTE
else
    FINAL_REMOTE=$LOCAL
fi

POST_BODY="{\"gitlog\":\"$GIT_LOG\",\"oper\":\"push\",\"remote\":\"$FINAL_REMOTE\"}"

curl -S -s -H "Content-Type: application/json" -d "$POST_BODY" http://localhost:5001/v1/hooks/push

exit 0