#!/bin/sh
# echo "PRE-PUSH LOG"

GIT_LOG=`git log --stat -1 HEAD | base64`
REMOTE=`git config --get remote.origin.url`
# echo $GIT_LOG

POST_BODY="{\"gitlog\":\"$GIT_LOG\",\"oper\":\"push\",\"remote\":\"$REMOTE\"}"

curl -S -s -H "Content-Type: application/json" -d "$POST_BODY" http://localhost:5001/v1/hooks/push

exit 0